import {
  IoAddCircleOutline,
  IoAddOutline,
  IoAlertCircleOutline,
  IoArrowBackOutline,
  IoArrowForward,
  IoBagAddOutline,
  IoBagHandleOutline,
  IoCameraOutline,
  IoCartOutline,
  IoChatbubbleEllipses,
  IoChatbubbleEllipsesOutline,
  IoChatbubblesOutline,
  IoCheckmarkCircleOutline,
  IoCheckmarkDoneOutline,
  IoCheckmarkOutline,
  IoChevronForward,
  IoClose,
  IoCloseOutline,
  IoCloudUploadOutline,
  IoCreateOutline,
  IoCubeOutline,
  IoEllipseOutline,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFlagOutline,
  IoGridOutline,
  IoHelpCircleOutline,
  IoHomeOutline,
  IoLeaf,
  IoLeafOutline,
  IoLocation,
  IoLocationOutline,
  IoLogOutOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoMailOutline,
  IoMailUnreadOutline,
  IoNotificationsOutline,
  IoOptionsOutline,
  IoPeopleOutline,
  IoPerson,
  IoPersonAddOutline,
  IoPersonOutline,
  IoReceiptOutline,
  IoSaveOutline,
  IoSearch,
  IoSearchOutline,
  IoSend,
  IoSendOutline,
  IoShieldCheckmarkOutline,
  IoSparkles,
  IoSparklesOutline,
  IoStatsChartOutline,
  IoTimeOutline,
  IoTrashOutline,
} from "react-icons/io5";

/**
 * Renders Ionicons-style icons (the names used throughout the original
 * app) on the web via react-icons/io5. Icons are imported individually
 * so the bundler can tree-shake unused ones.
 *
 *   <Icon name="cart-outline" size={20} color="#1E7A35" />
 */
const toPascal = (name) =>
  String(name || "")
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

const ICONS = {
  AddCircleOutline: IoAddCircleOutline,
  AddOutline: IoAddOutline,
  AlertCircleOutline: IoAlertCircleOutline,
  ArrowBackOutline: IoArrowBackOutline,
  ArrowForward: IoArrowForward,
  BagAddOutline: IoBagAddOutline,
  BagHandleOutline: IoBagHandleOutline,
  CameraOutline: IoCameraOutline,
  CartOutline: IoCartOutline,
  ChatbubbleEllipses: IoChatbubbleEllipses,
  ChatbubbleEllipsesOutline: IoChatbubbleEllipsesOutline,
  ChatbubblesOutline: IoChatbubblesOutline,
  CheckmarkCircleOutline: IoCheckmarkCircleOutline,
  CheckmarkDoneOutline: IoCheckmarkDoneOutline,
  CheckmarkOutline: IoCheckmarkOutline,
  ChevronForward: IoChevronForward,
  Close: IoClose,
  CloseOutline: IoCloseOutline,
  CloudUploadOutline: IoCloudUploadOutline,
  CreateOutline: IoCreateOutline,
  CubeOutline: IoCubeOutline,
  EyeOffOutline: IoEyeOffOutline,
  EyeOutline: IoEyeOutline,
  FlagOutline: IoFlagOutline,
  GridOutline: IoGridOutline,
  HelpCircleOutline: IoHelpCircleOutline,
  HomeOutline: IoHomeOutline,
  Leaf: IoLeaf,
  LeafOutline: IoLeafOutline,
  Location: IoLocation,
  LocationOutline: IoLocationOutline,
  LogOutOutline: IoLogOutOutline,
  LogoFacebook: IoLogoFacebook,
  LogoInstagram: IoLogoInstagram,
  LogoLinkedin: IoLogoLinkedin,
  MailOutline: IoMailOutline,
  MailUnreadOutline: IoMailUnreadOutline,
  NotificationsOutline: IoNotificationsOutline,
  OptionsOutline: IoOptionsOutline,
  PeopleOutline: IoPeopleOutline,
  Person: IoPerson,
  PersonAddOutline: IoPersonAddOutline,
  PersonOutline: IoPersonOutline,
  ReceiptOutline: IoReceiptOutline,
  SaveOutline: IoSaveOutline,
  Search: IoSearch,
  SearchOutline: IoSearchOutline,
  Send: IoSend,
  SendOutline: IoSendOutline,
  ShieldCheckmarkOutline: IoShieldCheckmarkOutline,
  Sparkles: IoSparkles,
  SparklesOutline: IoSparklesOutline,
  StatsChartOutline: IoStatsChartOutline,
  TimeOutline: IoTimeOutline,
  TrashOutline: IoTrashOutline,
};

export default function Icon({ name = "ellipse-outline", size = 20, color = "currentColor", className = "", style }) {
  const Component = ICONS[toPascal(name)] || IoEllipseOutline;
  return <Component size={size} color={color} className={className} style={style} aria-hidden="true" />;
}
