import {
  IoAddCircleOutline,
  IoAddOutline,
  IoAlertCircleOutline,
  IoArrowBackOutline,
  IoArrowDown,
  IoArrowForward,
  IoArrowUp,
  IoBagAddOutline,
  IoBagHandleOutline,
  IoBarChartOutline,
  IoBasketOutline,
  IoBookmarkOutline,
  IoBugOutline,
  IoCalendarOutline,
  IoCameraOutline,
  IoCardOutline,
  IoCartOutline,
  IoChatbubbleEllipses,
  IoChatbubbleEllipsesOutline,
  IoChatbubblesOutline,
  IoCheckmarkCircleOutline,
  IoCheckmarkDoneOutline,
  IoCheckmarkOutline,
  IoChevronDown,
  IoChevronDownOutline,
  IoChevronForward,
  IoChevronUp,
  IoChevronUpOutline,
  IoClose,
  IoCloseOutline,
  IoCloudOutline,
  IoCloudUploadOutline,
  IoCreateOutline,
  IoCubeOutline,
  IoDocumentTextOutline,
  IoDownloadOutline,
  IoEllipsisHorizontalOutline,
  IoEllipsisVerticalOutline,
  IoEllipseOutline,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFlagOutline,
  IoFlowerOutline,
  IoGridOutline,
  IoHappyOutline,
  IoHeart,
  IoHeartOutline,
  IoHelpCircleOutline,
  IoHomeOutline,
  IoLayersOutline,
  IoLeaf,
  IoLeafOutline,
  IoLocation,
  IoLocationOutline,
  IoLogOutOutline,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoMailOutline,
  IoMoonOutline,
  IoMailUnreadOutline,
  IoMenuOutline,
  IoNotificationsOutline,
  IoOptionsOutline,
  IoPartlySunnyOutline,
  IoPeopleOutline,
  IoPerson,
  IoPersonAddOutline,
  IoPersonOutline,
  IoPricetagOutline,
  IoRainyOutline,
  IoReceiptOutline,
  IoSaveOutline,
  IoSearch,
  IoSearchOutline,
  IoSend,
  IoSendOutline,
  IoSettingsOutline,
  IoShieldCheckmarkOutline,
  IoSparkles,
  IoSparklesOutline,
  IoStar,
  IoStarOutline,
  IoStatsChartOutline,
  IoStorefrontOutline,
  IoSunnyOutline,
  IoTimeOutline,
  IoTrendingDownOutline,
  IoTrendingUpOutline,
  IoTrashOutline,
  IoNavigateOutline,
  IoWalletOutline,
  IoWaterOutline,
} from "react-icons/io5";

/**
 * Renders Ionicons-style icons (the names used throughout the original
 * app) on the web via react-icons/io5. Icons are imported individually
 * so the bundler can tree-shake unused ones.
 *
 *   <Icon name="cart-outline" size={20} color="#1E7A35" />
 */
const toPascal = (name) =>
  String(name || "")
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

const ICONS = {
  AddCircleOutline: IoAddCircleOutline,
  AddOutline: IoAddOutline,
  AlertCircleOutline: IoAlertCircleOutline,
  ArrowBackOutline: IoArrowBackOutline,
  ArrowDown: IoArrowDown,
  ArrowForward: IoArrowForward,
  ArrowUp: IoArrowUp,
  BagAddOutline: IoBagAddOutline,
  BagHandleOutline: IoBagHandleOutline,
  BarChartOutline: IoBarChartOutline,
  BasketOutline: IoBasketOutline,
  BookmarkOutline: IoBookmarkOutline,
  BugOutline: IoBugOutline,
  CalendarOutline: IoCalendarOutline,
  CameraOutline: IoCameraOutline,
  CardOutline: IoCardOutline,
  CartOutline: IoCartOutline,
  ChatbubbleEllipses: IoChatbubbleEllipses,
  ChatbubbleEllipsesOutline: IoChatbubbleEllipsesOutline,
  ChatbubblesOutline: IoChatbubblesOutline,
  CheckmarkCircleOutline: IoCheckmarkCircleOutline,
  CheckmarkDoneOutline: IoCheckmarkDoneOutline,
  CheckmarkOutline: IoCheckmarkOutline,
  ChevronDown: IoChevronDown,
  ChevronDownOutline: IoChevronDownOutline,
  ChevronForward: IoChevronForward,
  ChevronUp: IoChevronUp,
  ChevronUpOutline: IoChevronUpOutline,
  Close: IoClose,
  CloseOutline: IoCloseOutline,
  CloudOutline: IoCloudOutline,
  CloudUploadOutline: IoCloudUploadOutline,
  CreateOutline: IoCreateOutline,
  CubeOutline: IoCubeOutline,
  DocumentTextOutline: IoDocumentTextOutline,
  DownloadOutline: IoDownloadOutline,
  EllipsisHorizontalOutline: IoEllipsisHorizontalOutline,
  EllipsisVerticalOutline: IoEllipsisVerticalOutline,
  EyeOffOutline: IoEyeOffOutline,
  EyeOutline: IoEyeOutline,
  FlagOutline: IoFlagOutline,
  FlowerOutline: IoFlowerOutline,
  GridOutline: IoGridOutline,
  HappyOutline: IoHappyOutline,
  Heart: IoHeart,
  HeartOutline: IoHeartOutline,
  HelpCircleOutline: IoHelpCircleOutline,
  HomeOutline: IoHomeOutline,
  LayersOutline: IoLayersOutline,
  Leaf: IoLeaf,
  LeafOutline: IoLeafOutline,
  Location: IoLocation,
  LocationOutline: IoLocationOutline,
  LogOutOutline: IoLogOutOutline,
  LogoFacebook: IoLogoFacebook,
  LogoInstagram: IoLogoInstagram,
  LogoLinkedin: IoLogoLinkedin,
  MailOutline: IoMailOutline,
  MoonOutline: IoMoonOutline,
  MailUnreadOutline: IoMailUnreadOutline,
  MenuOutline: IoMenuOutline,
  NotificationsOutline: IoNotificationsOutline,
  OptionsOutline: IoOptionsOutline,
  PartlySunnyOutline: IoPartlySunnyOutline,
  PeopleOutline: IoPeopleOutline,
  Person: IoPerson,
  PersonAddOutline: IoPersonAddOutline,
  PersonOutline: IoPersonOutline,
  PricetagOutline: IoPricetagOutline,
  RainyOutline: IoRainyOutline,
  ReceiptOutline: IoReceiptOutline,
  SaveOutline: IoSaveOutline,
  Search: IoSearch,
  SearchOutline: IoSearchOutline,
  Send: IoSend,
  SendOutline: IoSendOutline,
  SettingsOutline: IoSettingsOutline,
  ShieldCheckmarkOutline: IoShieldCheckmarkOutline,
  Sparkles: IoSparkles,
  SparklesOutline: IoSparklesOutline,
  Star: IoStar,
  StarOutline: IoStarOutline,
  StatsChartOutline: IoStatsChartOutline,
  StorefrontOutline: IoStorefrontOutline,
  SunnyOutline: IoSunnyOutline,
  TimeOutline: IoTimeOutline,
  TrendingDownOutline: IoTrendingDownOutline,
  TrendingUpOutline: IoTrendingUpOutline,
  TrashOutline: IoTrashOutline,
  NavigateOutline: IoNavigateOutline,
  WalletOutline: IoWalletOutline,
  WaterOutline: IoWaterOutline,
};

export default function Icon({ name = "ellipse-outline", size = 20, color = "currentColor", className = "", style }) {
  const Component = ICONS[toPascal(name)] || IoEllipseOutline;
  return <Component size={size} color={color} className={className} style={style} aria-hidden="true" />;
}
